---
- name: Install Vector via direct download
  block:
    - name: Download Vector RPM package
      get_url:
        url: https://packages.timber.io/vector/0.35.0/vector-0.35.0-1.x86_64.rpm
        dest: /tmp/vector.rpm

    - name: Install Vector from local RPM
      yum:
        name: /tmp/vector.rpm
        state: present
      become: yes

    - name: Remove temporary RPM file
      file:
        path: /tmp/vector.rpm
        state: absent
  become: yes

- name: Ensure Vector config directory exists
  file:
    path: /etc/vector
    state: directory
    mode: 0755
  become: yes

- name: Create minimal Vector config
  copy:
    dest: /etc/vector/vector.toml
    content: |
      [sources.in]
      type = "stdin"

      [sinks.out]
      type = "console"
      inputs = ["in"]
      encoding.codec = "json"
    mode: 0644
  become: yes

- name: Start and enable Vector service
  systemd:
    name: vector
    state: started
    enabled: yes
  become: yes